{
 "title": "ETH 2.0",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "node_job", "query": "beacon node" },
   { "name": "validator_job", "query": "validator" }
  ]
 },
 "panels": [
  {
   "title": "VALIDATOR",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Measured earnings (ETH)",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Projected earnings (ETH)",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Daily earnings (ETH)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(deriv(validator_balance[1d])*3600*24)",
     "legendFormat": "Projected"
    },
    {
     "expr": "sum(delta(validator_balance[1d]))",
     "legendFormat": "Measured"
    }
   ]
  },
  {
   "title": "Successful Attestations & Aggregations per hour",
   "type": "graph",
   "description": "Should be remain on the same level. On average 1 attestation per validator per epoch (12s * 32 slots = 384s).  So per validator we should see on avg 9.375 attestations per hour.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(validator_successful_attestations[3600s])*3600)",
     "legendFormat": "Attestations"
    },
    {
     "expr": "sum(rate(validator_successful_aggregations[3600s])*3600)",
     "legendFormat": "Aggregations"
    }
   ]
  },
  {
   "title": "Hourly",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(validator_balance[1h]))"
    }
   ]
  },
  {
   "title": "Hourly (proj.)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(deriv(validator_balance[15m])*3600)"
    }
   ]
  },
  {
   "title": "Daily",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(validator_balance[1d]))"
    }
   ]
  },
  {
   "title": "Daily (proj.)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(deriv(validator_balance[3h])*86400)"
    }
   ]
  },
  {
   "title": "Weekly",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(validator_balance[1w]))"
    }
   ]
  },
  {
   "title": "Weekly (proj.)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(deriv(validator_balance[1d])*604800)"
    }
   ]
  },
  {
   "title": "Monthly",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(validator_balance[30d]))"
    }
   ]
  },
  {
   "title": "Monthly (proj.)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(deriv(validator_balance[1w])*2592000)"
    }
   ]
  },
  {
   "title": "Total earnings (ETH)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(validator_balance)-count(validator_balance)*32"
    }
   ]
  },
  {
   "title": "Weekly earnings (ETH)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(deriv(validator_balance[1w])*3600*24*7)",
     "legendFormat": "Projected"
    },
    {
     "expr": "sum(delta(validator_balance[1w]))",
     "legendFormat": "Measured"
    }
   ]
  },
  {
   "title": "Validator main info",
   "type": "table",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "label_replace(max by(pubkey) (validator_balance), \"pubkey\", \"$1\", \"pubkey\", \"(.{10}).*\")"
    },
    {
     "expr": "label_replace(max by(pubkey) (validator_statuses), \"pubkey\", \"$1\", \"pubkey\", \"(.{10}).*\")"
    },
    {}
   ]
  },
  {
   "title": "Validator vote summary",
   "type": "table",
   "description": "This panel will count only the votes done since your validator process started",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 10 },
   "targets": [
    {
     "expr": "label_replace(max by(pubkey) (validator_successful_attestations) , \"pubkey\", \"$1\", \"pubkey\", \"(.{10}).*\")"
    },
    {
     "expr": "label_replace(max by (pubkey)(validator_failed_attestations)  , \"pubkey\", \"$1\", \"pubkey\", \"(.{10}).*\")"
    },
    {
     "expr": "label_replace(max by (pubkey)(validator_successful_aggregations)    , \"pubkey\", \"$1\", \"pubkey\", \"(.{10}).*\")"
    },
    {
     "expr": "label_replace(max by (pubkey) (validator_failed_aggregations) , \"pubkey\", \"$1\", \"pubkey\", \"(.{10}).*\")"
    },
    {
     "expr": "label_replace(max by (pubkey) (validator_successful_proposals) , \"pubkey\", \"$1\", \"pubkey\", \"(.{10}).*\")"
    },
    {
     "expr": "label_replace(max by (pubkey) (validator_failed_proposals) , \"pubkey\", \"$1\", \"pkey\", \"(.{10}).*\")"
    }
   ]
  },
  {
   "title": "Total balance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "ETH" }
   ],
   "targets": [
    { "expr": "sum(validator_balance)", "legendFormat": "Total balance" }
   ]
  },
  {
   "title": "BEACON / NETWORK",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 19 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "1", "legendFormat": "NODE" }
   ]
  },
  {
   "title": "SERVER",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 8, "x": 12, "y": 19 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "1", "legendFormat": "NODE" }
   ]
  },
  {
   "title": "ALERTS",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 4, "x": 20, "y": 19 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Participation Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "total_voted_target_balances/total_eligible_balances",
     "legendFormat": "Participation rate"
    }
   ]
  },
  {
   "title": "Number of slot behind",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "beacon_clock_time_slot-beacon_head_slot"
    }
   ]
  },
  {
   "title": "Node process started",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 20 },
   "format": "h",
   "valueName": "current",
   "targets": [
    {
     "expr": "(time()-process_start_time_seconds{job=\"$node_job\"})/3600"
    }
   ]
  },
  {
   "title": "Validator process started",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 20 },
   "format": "h",
   "valueName": "current",
   "targets": [
    {
     "expr": "(time()-process_start_time_seconds{job=\"$validator_job\"})/3600"
    }
   ]
  },
  { "title": "All alerts", "type": "alertlist", "gridPos": { "h": 12, "w": 4, "x": 20, "y": 20 } },
  {
   "title": "Peers connected",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "p2p_peer_count{state=\"Connected\"}"
    }
   ]
  },
  {
   "title": "Mem usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "decbytes", "label": "mem usage" }
   ],
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Total balance all validators",
   "type": "graph",
   "description": "This graph is made for trading purpose mostly.\nSupposing that if a lot of validators are exiting, price is gonna dump.\n\nAlso this can prevent to exit while exiting queue is too long, same for depositing while pending queue is too long.\n\n",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short", "label": "ETH" }
   ],
   "targets": [
    {
     "expr": "validators_total_balance{state=\"Active\"} / 10e8",
     "legendFormat": "Active"
    },
    {
     "expr": "validators_total_balance{state=\"Pending\"} / 10e8",
     "legendFormat": "Pending"
    },
    {
     "expr": "validators_total_balance{state=\"Exiting\"} / 10e8",
     "legendFormat": "Exiting"
    }
   ]
  },
  {
   "title": "Hourly log type counter",
   "type": "bargauge",
   "description": "This panel won't have consistant values during the first hour of the node started process",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 26 },
   "targets": [
    {
     "expr": "sum(delta(log_entries_total{job=\"$node_job\", level=\"error\"}[1h]))",
     "legendFormat": "error"
    },
    {
     "expr": "sum(delta(log_entries_total{job=\"$node_job\", level=\"warning\"}[1h]))",
     "legendFormat": "warning"
    }
   ]
  },
  {
   "title": "OTHER STUFF / CURRENTLY NOT USED",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "1", "legendFormat": "NODE" }
   ]
  },
  {
   "title": "Validator balance",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short", "label": "ETH" }
   ],
   "targets": [
    {
     "expr": "label_replace(validator_balance, \"pubkey\", \"$1\", \"pubkey\", \"(0x.{8}).*\")",
     "legendFormat": "{{pubkey}}"
    }
   ]
  },
  {
   "title": "Alert: Number of slot behind",
   "type": "graph",
   "gridPos": { "h": 1, "w": 4, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "beacon_clock_time_slot-beacon_head_slot",
     "legendFormat": "node slots behind"
    }
   ]
  },
  {
   "title": "Alert: Process down",
   "type": "graph",
   "gridPos": { "h": 1, "w": 4, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "up", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Alert: Crashed",
   "type": "graph",
   "gridPos": { "h": 1, "w": 4, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(log_entries_total{level=\"fatal\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Alert: Hourly earning <= 0",
   "type": "graph",
   "gridPos": { "h": 1, "w": 4, "x": 8, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(validator_balance[1h]))",
     "legendFormat": "validators balance on 1h"
    }
   ]
  },
  {
   "title": "Alert: More than 50 errors in 1h",
   "type": "graph",
   "gridPos": { "h": 1, "w": 4, "x": 8, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(log_entries_total{job=\"beacon node\", level=\"error\"}[1h]))",
     "legendFormat": "errors"
    },
    {
     "expr": "sum(delta(log_entries_total{job=\"beacon node\", level=\"warning\"}[1h]))",
     "legendFormat": "warnings"
    }
   ]
  },
  {
   "title": "Alert: Validator has been slashed",
   "type": "graph",
   "gridPos": { "h": 1, "w": 4, "x": 8, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(validator_statuses, \"pubkey\", \"$1\", \"pubkey\", \"(.{10}).*\")",
     "legendFormat": "{{pubkey}}"
    }
   ]
  }
 ]
}